version: "3"
networks:
  event-photos-local-dev:
    external: true
services:
  "event-photos":
    build: $EVENT_PHOTOS_HOME/local-dev
    container_name: "event-photos"
    networks:
      - event-photos-local-dev
    environment:
      - LOCAL=true
      - BASE_URL=localhost
      - DEBUGGER_ARGS=--continue
      - DATABASE_URL=event-photos-db
      - DATABASE_PORT=5432
      - DATABASE_USER=event-photos
      - DATABASE_PASSWORD=event-photos
      - DATABASE_SCHEMA=event-photos
    ports:
      - "8080"
      - "40000:40000"
    volumes:
      - "$EVENT_PHOTOS_HOME/backend/event-photos:/srv/package"
