version: '3'
networks:
  event-photos-local-dev:
    external: true
services:
  event-photos:
    build: $EVENT_PHOTOS_HOME/backend
    container_name: 'event-photos'
    networks:
      - event-photos-local-dev
    env_file: "$EVENT_PHOTOS_HOME/backend/event-photos/secrets.env"

    ports:
      - '8080'
      - '40000:40000'
    volumes:
      - '$EVENT_PHOTOS_HOME/backend/event-photos:/srv/package'

